module.exports = {
    data: {
        name: "voiceline",
        description: "Sends a random Teddy Bloxpin voiceline",
        "integration_types": [0, 1],
        "contexts": [0, 1, 2]
    },
    async execute(interaction) {
        const voicelines = [
                "Sometimes I wonder if we were put here for a reason, düd.",
                "Don't try to steal from Jeff, man... he will make you pay. Should call him Jeff the Killer, or something.",
                "Eheeheehee, I'm terrifying man. Showed those Eye thingies what for. It was me and Bob, we dropped down... they weren't ready.",
                "Oye, if you hear me scrambling about there somewhere, don't be alarmed, düd. A guy's gotta eat.",
                "I s- I- I seen a weird creature, düd. Looked like that eyeball guy, but like... purple and weird. Ask Bob, he'll tell you!",
                "Jeff charges so much for his stuff, düd. Eheehee... I- I mean, who's got dat kinda plata, y'know?",
                "Bob wants to make friends with that Timothy guy... it's a- it's- it's a bug, man!",
                "Find any goods out there? Eheehee... I plan to take a look myself.",
                "Oye, stay far away from room 60, düd. Freaky stuff!",
                "I shined a light at Jeff, once. To see what he looks like, y'know? Oye hombre... nunca más.",
                "Oye! Stay a while, if you like. We are the only creatures here who won't try to eat you, hombre.",
                "Bob needs to eat something, man. Recently he's been looking like a bag of bones. Real quiet, too.",
                "Oye, that macho-meat-düd came in here a while ago, alm- uh- almost destroyed the place! Uff, man! Calm down!",
                "Say, hombre... do you believe in... y'know... a higher power?",
                "Oye... who do you think built this place? The Hotel, I mean.",
                "So... how'd you get here, düd? What? What do you mean you don't know?",
                "My earring? Was given to me by mi amor, düd. I will see her again someday.",
                "Sometimes I like to knock on the walls, scare the pants off the humans. So funny, düd.",
                "Oye, hombre... if you die, GO AGANE! Always go agane.",
                "¿Qué? What do you want?",
                "Bob told me he saw one of those sparkley-thingies, but it wasn't blue. No manches, düd! Not possible!",
                "Eheeheehee! You look funny, hombre!",
                "Jeff makes a banger sandwich, düd. You should try it some time.",
                "People- people call me small. Nah, man. When I spawned in, I was much smaller. Wait, ehh...",
                "Bob says there's some weird stuff going on around the Hotel. You seen anything weird?",
                "Bob has a nasty kick, man. Don't get on his bad side, comprende?",
                "Sometimes I hate Jeff, düd... I gotta scrounge for so many coins just to eat dinner, man.",
                "Doors, doors, doors all around me.",
                "Monsters are everywhere trying to get us... this is so trash, düd.",
                "Ehh... I'm bored. All this dusty wallpaper gives me the blues!",
                "Eheehee... do I smell gold in your pockets? You w- you- you wouldn't mind loaning me some, would you, düd?",
                "Hey düd... can you loan me some gold? I- I'll pay you back, I swear!",
                "Me and Bob are trying to settle something here... who do you think could lift the most?",
                "I like Jeff's other places much better. Dis is alright, though. Eheehee.",
                "Bob here asked me to introduce you two. Bob, human. Human, Bob.",
                "Man... I think Bob is upset with me. He's giving me the silent treatment.",
                "Bob looks a little different today, düd. Maybe a new haircut?",
                "Eheehee... just thought of a funny joke, düd. Oye, Bob! Knock knock! Bob, knock knock! ...Bob? Oye, Bob! Eh, nevermind.",
                "That smiley-guy came through here once, y'know. Broke all the lights, I had- I- I had to fix 'em. He got in a real bad fight with Bob, too.",
                "Oye, human. Bob says you smell! Eheeheehee...",
                "Eheeheehee! Yeah düd, me and Bob go way back. We met back in... eh... uh... I don't really remember!",
                "Oye, you like my wristbands, eh? To be real, I don't remember where I got them... they've just kinda always been there, düd.",
                "I been thinking of starting a business just like Jeff, düd. I could dig out some tunnels, call it 'Goblino's Shortcuts'! Working on the name.",
                "Oye... why do all you humans come through here anyway? What- what's so important about room 100, düd?",
                "Me and Bob were in the greenhouse this one time, he stepped on one of those spiky-plant-things, düd. Scared him so bad... haven't heard a peep out of him since. Speechless!",
                "I wonder how Jeff gets all his stock, düd. Can you imagine him scavenging through the hallways? Eheehee! ¡Es gracioso, hombre!",
                "Phew! Something stinks, hombre! The smell gets way worse closer to room 100. What do you think it is, düd?",
                "I miss her, man...",
                "I have this recurring dream... of tasting the b- th- the best soda in the whole world! Muy delicioso!",
                "Bob here told me his special passcode is 'BOBRULZ'. Wonder what dat means, düd?",
                "Had a dream last night, was being chased by those screechy-düds, uff... but I was saved! So it's okay.",
                "I wonder what's behind Jeff in that little hallway there, düd.",
                "Jeff was real smart to set up shop here, düd. Customers flow in like agua!",
                "I set some traps and used one of those cross-thingies on that meat-düd once, but it turned bright rojo, red! Bob don't believe me, thinks I hit my head. Eheehee, like, I know what I saw, hombre!",
                "Oye, hombre... I had the weirdest dream. I was m- muy pequeño, and I was fighting dat macho-meat-düd! Weird, right? Eheehee!",
                "Hmm? Y- you think I'm a WHAT, hombre? A duende? No man, I'm a goblino! El Goblino! That's me, and don't forget it!",
                "Oye, hombre... you got the time? We gotta be outta here by midnight... don't wanna be out at midnight...",
                "Oye, hombre... i- is that a little me I see on your shoulder? Nevermind, I think I'm seeing things...",
                "Eheehee... Y- You look just like me, düd! ¡Muy guapo!",
                "Oye... if the water turns black, RUN AWAY hombre! It's dangerous!",
                "You seen t- those freaky giggly-düds on the ceiling? One got the jump on Bob, scared us both silly! Eheehee!",
                "H-how do those giggly-düds get so big, hombre? The regular giggly-düds are freaky enough!",
                "Y-yo-you noticed how those giggly-düds and those screechy-düds look alike? I wonder what it means, hombre.",
                "All those fly-thingies stink, but dey taste real good. A open flame can do wonders, düd, i wonder how those giggly-düds taste?",
                "You seen those glowy fly-thingies, hombre? They hate light! Lucky for me, yo tengo mis ojos Goblinos. Night vision, hombre! Eheehee!",
                "Oye... a little goblino like me can barely breathe down here! How do you do it, düd?",
                "You seen that blue ghosty-düd in the dining hall? He's guarding all the good eats, hombre!",
                "You seen that freaky door in the hospital with the skull on it? Weird!",
                "Oye hombre... could you get me a bite? Eheeheehee...",
                "You been to the courtyard yet düd? I would lay out there on the grass and stare at the stars, if there were any...",
                "Steer clear of that orange smokey stuff, hombre. That stuff's stinky! Pee-yew!",
                "I had a dream that I had a whole crate of gold bars...",
                "...Why did I have to wake up, hombre?! Take me back!",
                "I wonder if we could fish in here, düd. You- you got any bait?",
                "Oye... why do you think the Mines are here underneath the Hotel? Who built this stuff, man? Weird!",
                "I like dis place much better than the Hotel, düd. Wait... why is there a mineshaft underneath a hotel, anyways?",
                "I think there's a little creature living in the walls, hombre... You down for a little pest control? Eheehee!",
                "Looking good, hombre! M- must have burned off some calories running from those giant giggly-düds! Eheeheehee!",
                "I think that macho-meat-düd followed you down here, düd. We used to be safe from dat guy down here!",
                "Oye, hombre... what's up with that big ole' vine over dere? It gives me the creeps! Eheehee!",
                "Oye, hombre... I was searching about earlier, found a bunch of good loot...",
                "...Before I knew it, POOF! Something came out of the wall and robbed me blind!",
                "Oye, whats up with all those dead screechy-düds? Gross, man!",
                "You ever notice how all those monsters are more vicious down here, hombre? Uff, this stuff is dangerous!",
                "That little niña in the window keeps trying to swipe Jeff's items without paying! Make sure you pay for them, düd.",
                "Gold? I love gold! I would love items too, but that little niña in the window always beats me to the chase.",
                "Oye, if you're wondering why Jeff don't got something in stock, chances are that little niña in the window beat him to it.",
                "Be careful in the agua hombre...It's pretty dirty, scary monsters can hide in dere!'",
            ];

        const voiceline = voicelines[Math.floor(Math.random() * voicelines.length)];
    
        await interaction.reply({ content: `${voiceline}`, ephemeral: false });
      },
}